import AppKit
import Foundation
import os

/// 주입된 페이스트보드의 changeCount를 폴링해 변경 시 분류·저장한다.
/// 내용 읽기는 프라이버시 게이트를 통과할 때만. 로그에 내용·경로를 남기지 않는다.
@MainActor
final class ClipboardMonitor {
    var isEnabled = false { didSet { if !isEnabled { store.pasteboardBlocked = false } } }
    private(set) var lastChangeCount: Int
    private let store: ClipboardStore
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lockObservers: [NSObjectProtocol] = []
    private var allowDefaultReadOnce = false
    private let logger = Logger(subsystem: "com.holyshine11.opennotch", category: "clipboard")

    private static let excludedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"), .openNotchSource,
    ]

    init(store: ClipboardStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        stop()
        let t = Timer(timeInterval: Constants.clipboardPollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        t.tolerance = Constants.clipboardPollInterval / 3
        RunLoop.main.add(t, forMode: .common)
        timer = t
        let center = DistributedNotificationCenter.default()
        lockObservers = [
            center.addObserver(forName: .init("com.apple.screenIsLocked"), object: nil, queue: .main) { [weak self] _ in
                MainActor.assumeIsolated { self?.timer?.fireDate = .distantFuture }
            },
            center.addObserver(forName: .init("com.apple.screenIsUnlocked"), object: nil, queue: .main) { [weak self] _ in
                MainActor.assumeIsolated { self?.timer?.fireDate = Date() }
            },
        ]
    }

    func stop() {
        timer?.invalidate(); timer = nil
        lockObservers.forEach { DistributedNotificationCenter.default().removeObserver($0) }
        lockObservers.removeAll()
    }

    /// 사용자가 명시적으로 켤 때: `.default` 상태에서도 1회 읽어 시스템 알림이 사용자 동작에 귀속되게 한다.
    func enableWithUserAction() {
        isEnabled = true
        allowDefaultReadOnce = true
        lastChangeCount = pasteboard.changeCount - 1
        poll()
    }

    func poll() {
        guard isEnabled, pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let allowed = canReadContents()
        allowDefaultReadOnce = false
        guard allowed else { store.pasteboardBlocked = true; return }
        store.pasteboardBlocked = false
        let types = pasteboard.types ?? []
        guard !types.contains(where: Self.excludedTypes.contains) else { return }

        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            store.insert(.files(urls.map(\.path)), imagePNG: nil)
        } else if types.contains(.png) || types.contains(.tiff) {
            guard let png = pngData(from: pasteboard), png.count <= Constants.clipboardMaxImageBytes else { return }
            store.insert(.image(byteCount: png.count), imagePNG: png)
        } else if let text = pasteboard.string(forType: .string), !text.isEmpty {
            store.insert(.text(text), imagePNG: nil)
        }
    }

    /// 테스트용: `.default` 1회 읽기 플래그가 아직 소비되지 않았는지.
    var isDefaultReadPending: Bool { allowDefaultReadOnce }

    // MARK: 내부

    private func canReadContents() -> Bool {
        guard pasteboard.name == .general else { return true }
        if #available(macOS 15.4, *) {
            switch pasteboard.accessBehavior {
            case .alwaysAllow: return true
            case .default:
                return allowDefaultReadOnce
            default: return false
            }
        }
        return true
    }

    private func pngData(from pb: NSPasteboard) -> Data? {
        if let png = pb.data(forType: .png) { return png }
        guard let tiff = pb.data(forType: .tiff), tiff.count <= Constants.clipboardMaxImageBytes,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
