import AppKit
import Foundation
import Testing
@testable import OpenNotch

@MainActor
@Suite struct ClipboardMonitorTests {
    private func make() throws -> (ClipboardMonitor, ClipboardStore, NSPasteboard) {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("clipmon-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let store = ClipboardStore(directory: dir)
        let pb = NSPasteboard(name: NSPasteboard.Name("com.holyshine11.opennotch.test.\(UUID().uuidString)"))
        let monitor = ClipboardMonitor(store: store, pasteboard: pb)
        monitor.isEnabled = true
        return (monitor, store, pb)
    }

    @Test func capturesPlainText() throws {
        let (m, store, pb) = try make()
        pb.clearContents(); pb.setString("hello", forType: .string)
        m.poll()
        #expect(store.items.first?.text == "hello")
        #expect(store.items.first?.kind == .text)
    }

    @Test func unchangedChangeCountDoesNothing() throws {
        let (m, store, pb) = try make()
        pb.clearContents(); pb.setString("once", forType: .string)
        m.poll(); m.poll()
        #expect(store.items.count == 1)
    }

    @Test func skipsConcealedTransientAndOwnItems() throws {
        let (m, store, pb) = try make()
        for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            pb.clearContents()
            pb.setString("secret", forType: .string)
            pb.setString("1", forType: NSPasteboard.PasteboardType(type))
            m.poll()
        }
        pb.clearContents(); pb.setString("mine", forType: .string); pb.setString("1", forType: .openNotchSource)
        m.poll()
        #expect(store.items.isEmpty)
    }

    @Test func classifiesFilesOverImageOverText() throws {
        let (m, store, pb) = try make()
        pb.clearContents()
        pb.writeObjects([URL(fileURLWithPath: "/tmp/x.txt") as NSURL])
        pb.setString("/tmp/x.txt", forType: .string)
        m.poll()
        #expect(store.items.first?.kind == .files)
        #expect(store.items.first?.filePaths == ["/tmp/x.txt"])

        pb.clearContents()
        let png = NSImage(size: NSSize(width: 2, height: 2)).pngData()
        pb.setData(png, forType: .png)
        pb.setString("caption", forType: .string)
        m.poll()
        #expect(store.items.first?.kind == .image)
        #expect(store.imageURL(for: store.items[0].id).map { FileManager.default.fileExists(atPath: $0.path) } == true)
    }

    @Test func urlStringBecomesURLKind() throws {
        let (m, store, pb) = try make()
        pb.clearContents(); pb.setString("https://example.com/path", forType: .string)
        m.poll()
        #expect(store.items.first?.kind == .url)
    }

    @Test func disabledMonitorIgnoresChanges() throws {
        let (m, store, pb) = try make()
        m.isEnabled = false
        pb.clearContents(); pb.setString("ignored", forType: .string)
        m.poll()
        #expect(store.items.isEmpty)
    }

    @Test func oversizedImageIsDropped() throws {
        let (m, store, pb) = try make()
        pb.clearContents()
        pb.setData(Data(count: Constants.clipboardMaxImageBytes + 1), forType: .png)
        m.poll()
        #expect(store.items.isEmpty)
    }
}

private extension NSImage {
    func pngData() -> Data {
        let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: Int(size.width), pixelsHigh: Int(size.height), bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
        return rep.representation(using: .png, properties: [:])!
    }
}
